### ISSUE TITLE
Does not report properly negative temperatures

### ISSUE THREAD

**Issue by joseluu** [jlz3008/lm75#4]
I did this fix to make it work:

float TempI2C_LM75::getTemp()
{
	union {
		unsigned short tempX;
		short tempS;
	} temperature;

	temperature.tempX = getReg(temp_reg);
	return (temperature.tempS / 256.0F);
}

//-------------------------------------------------------------------------------
unsigned short TempI2C_LM75::getReg(LM75Register reg)
{

**Comment by jlz3008** [comment]
Thanks @joseluu 
I can't test it, only compile test, but I guess it is OK.
